# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2e6f6ef80582ef31144c56d9b1537cb6225e3f40a81fd39fad0bdc7200b4fac5f1de92ef3e502be63e2477ac8180882daec998f61fb22e29777a130693cc0497

test:
  secret_key_base: 69ad72f8f98ff35557ca5e37f8af207e60b61212aad2203a91b604d974a8af58629c1315c66d02bfb6778f9e17ee403c13fecb022688b61b1c919b59fcf44885

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
